### ISSUE TITLE
Update requests to have User-Agent field

### ISSUE THREAD

**Issue by chatterchats** [Millefeuille42/HelldiversIITools#4]
## Strategic Briefing
Add User-Agent header to requests

**Critical Assessment**
Allows for better tracking on the end point developers ends, allowing us to reach out if needed should something unexpected happen (Such as: Dramatic increase in requests beyond reasonable amounts - think 80-90 requests a minute)

**Innovative Solution**
Simple line add in `pkg/shared/helldivers/lib/client.go`
`req.Header.Set("User-Agent", "Helldivers II Tools")`

**Additional Intel**
None

**Comment by Millefeuille42** [comment]
Solved by #3
